"""Chat service — owns the graph and turns its stream into UI events."""

from __future__ import annotations

import logging
import uuid
from collections.abc import AsyncIterator
from typing import Any

from core.categories import CATEGORIES, DEFAULT_CATEGORY
from graph.builder import build_graph
from services.analysis_service import AnalysisService
from services.history_service import ContextHistory
from services.llm_service import LLMService
from services.router_service import RouterService
from services.summary_service import SummaryService
from services.vector_service import VectorService

logger = logging.getLogger(__name__)

# "custom"   -> status/route events written by the nodes
# "messages" -> the answer's tokens as the LLM produces them
_STREAM_MODES = ["custom", "messages"]


def scoped_session_id(user_id: str, session_id: str) -> str:
    """Namespace a browser-supplied chat id under the account that owns it.

    Chat ids are generated by the client, so on their own they are only as
    unguessable as the browser made them. Binding the owner into the id is what
    makes a filing unreachable from another account: two users who somehow
    picked the same chat id still get two different collections, and there is
    no id a signed-in user can send that resolves to someone else's uploads.
    """
    return f"{user_id}:{session_id}"


class ChatService:
    """Entry point for the whole pipeline: upload a filing, then ask about it.

    A query runs ``retrieve -> router -> <category>`` (see
    :mod:`graph.builder`) and every step is streamed back to the caller.
    """

    def __init__(self, model: str, embedding_model: str, base_url: str) -> None:
        llm = LLMService(
            model=model,
            embedding_model=embedding_model,
            base_url=base_url,
        )
        self.vector = VectorService(embeddings=llm.embeddings)
        # The same model that answers also keeps the conversation summaries;
        # `HistoryService` is handed this in main, and calls it off the
        # critical path once a dossier grows long enough to need it.
        self.summary = SummaryService(llm=llm)
        self.graph = build_graph(
            vector=self.vector,
            router=RouterService(llm=llm),
            analysis=AnalysisService(llm=llm),
        )
        logger.info("ChatService ready")

    async def upload_file(
        self,
        file_bytes: bytes,
        filename: str,
        session_id: str,
    ) -> dict[str, Any]:
        """Ingest an uploaded filing into this chat's own collection."""
        chunks = await self.vector.ingest_file(file_bytes, filename, session_id)
        return {
            "status": "ok",
            "filename": filename,
            "chunks_ingested": chunks,
            "session_id": session_id,
        }

    def delete_session(self, session_id: str) -> dict[str, Any]:
        """Throw away every filing this chat uploaded."""
        deleted = self.vector.delete_session(session_id)
        return {"status": "ok", "session_id": session_id, "deleted": deleted}

    async def query_stream(
        self,
        query: str,
        session_id: str = "",
        title: str = "",
        history: ContextHistory | None = None,
    ) -> AsyncIterator[dict[str, Any]]:
        """Run a query through the graph, yielding events as they happen.

        ``title`` is the name this chat already carries; pass it blank for a
        chat that has none and the router names it, reporting the name back as
        a ``title`` event and again on ``done``.

        ``history`` is what this dossier has already established, assembled by
        :class:`services.history_service.HistoryService`. Passing it is what
        makes a follow-up question a follow-up rather than a fresh start;
        leaving it out answers the question on its own, as before.

        Each yielded dict is ready to emit over Socket.IO::

            {"event": "run_started", "run_id": "..."}
            {"event": "status", "stage": "retrieve"}
            {"event": "title",  "title": "FY2024 Revenue Review"}
            {"event": "route",  "category": "risks"}
            {"event": "token",  "content": "..."}
            {"event": "done",   "run_id": "...", "category": "risks", "title": "..."}
        """
        run_id = uuid.uuid4().hex
        history = history or ContextHistory()
        logger.info(
            "Run %s started: %r (session=%s, history=%d msg/~%d tokens)",
            run_id,
            query[:80],
            session_id,
            len(history.messages),
            history.tokens,
        )
        yield {"event": "run_started", "run_id": run_id}

        category = DEFAULT_CATEGORY
        graph_input = {
            "query": query,
            "session_id": session_id,
            "title": title,
            "summary": history.summary,
            "history": history.messages,
        }

        # A fresh thread id per run, so concurrent runs never share state.
        config = {"configurable": {"thread_id": run_id}}

        async for mode, chunk in self.graph.astream(
            graph_input, config=config, stream_mode=_STREAM_MODES
        ):
            if mode == "custom":
                if chunk.get("event") == "route":
                    category = chunk.get("category", category)
                elif chunk.get("event") == "title":
                    title = chunk.get("title", title)
                yield chunk

            elif mode == "messages":
                message, metadata = chunk
                # Only the analysis nodes stream to the user — the router's own
                # LLM call comes through here too and must be dropped.
                if metadata.get("langgraph_node") not in CATEGORIES:
                    continue
                content = str(message.text)
                if content:
                    yield {"event": "token", "content": content}

        logger.info("Run %s finished (category=%s)", run_id, category)
        yield {"event": "done", "run_id": run_id, "category": category, "title": title}
